server:
  port: 20081
  context-path: /
  

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.67.0:3306/db_jxc2
    username: java
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false